version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - dev

  goapi:
    build: 
      context: ./goapi
      dockerfile: Dockerfile.dev
    container_name: goapi
    ports:
      - "7999:7999"
    depends_on:
      - mongodb
    networks:
      - dev

  webapp:
    build:
      context: ./vue-front-end
      dockerfile: Dockerfile.dev
    container_name: vuefrontend
    ports:
      - "8080:8080"
    volumes:
      - ./vuefrontend:/app
    depends_on:
      - goapi
    networks:
      - dev


volumes:
  mongo-data:

networks:
  dev:
